<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:TalendMetadata="http://www.talend.org/metadata/connection/2010" xmlns:orgomg.cwm.resource.relational="http:///orgomg/cwm/resource/relational.ecore">
  <TalendMetadata:DatabaseConnection xmi:id="_isoeoHlfEe65NalLni4mbw" name="sqlqdi4" id="_txEMpUZXEe6jh5TnZ61a6A" label="sqlqdi4" dataPackage="_isoernlfEe65NalLni4mbw" DatabaseType="Microsoft SQL Server" DriverClass="net.sourceforge.jtds.jdbc.Driver" URL="jdbc:jtds:sqlserver://20.204.123.250:1433/MrunalBikeStores;" dbVersionString="JTDS" Port="1433" Username="qdimainuser" Password="enc:system.encryption.key.v1:uOSe+fhKD/AcEA7QWoxMlZECRW5eQEd5LAG2i/R9Twk9f7jz0FioDg==" ServerName="20.204.123.250" DatasourceName="" FileFieldName="" SID="MrunalBikeStores" SqlSynthax="" StringQuote="" NullChar="" DbmsId="id_MSSQL" ProductId="SQL_SERVER" AdditionalParams="" StandardSQL="true" SQLMode="false" UiSchema="production" supportNLS="false">
    <taggedValue xmi:id="_isoeoXlfEe65NalLni4mbw" tag="Is Conn Need Reload" value="true"/>
    <taggedValue xmi:id="_isoeonlfEe65NalLni4mbw" tag="package filter" value=""/>
    <taggedValue xmi:id="_isoeo3lfEe65NalLni4mbw" tag="Status" value=""/>
    <taggedValue xmi:id="_isoepHlfEe65NalLni4mbw" tag="Version" value="0.1"/>
    <taggedValue xmi:id="_isoepXlfEe65NalLni4mbw" tag="Purpose" value=""/>
    <taggedValue xmi:id="_isoepnlfEe65NalLni4mbw" tag="Description" value=""/>
    <taggedValue xmi:id="_isoep3lfEe65NalLni4mbw" tag="Author" value=""/>
    <taggedValue xmi:id="_isoeqHlfEe65NalLni4mbw" tag="otherParameter"/>
    <taggedValue xmi:id="_isoeqXlfEe65NalLni4mbw" tag="DB ProductName" value="Microsoft SQL Server"/>
    <taggedValue xmi:id="_isoeqnlfEe65NalLni4mbw" tag="DB ProductVersion" value="16.00.1000"/>
    <taggedValue xmi:id="_isoeq3lfEe65NalLni4mbw" tag="DB IdentifierQuoteString" value="&quot;"/>
    <parameters xmi:id="_isoerHlfEe65NalLni4mbw" key="CONN_PARA_KEY_USERNAME" value="qdimainuser"/>
    <parameters xmi:id="_isoerXlfEe65NalLni4mbw" key="CONN_PARA_KEY_MAPRDB_TABLE_NS_MAPPING" value=""/>
  </TalendMetadata:DatabaseConnection>
  <orgomg.cwm.resource.relational:Catalog xmi:id="_isoernlfEe65NalLni4mbw" name="MrunalBikeStores" dataManager="_isoeoHlfEe65NalLni4mbw">
    <ownedElement xsi:type="orgomg.cwm.resource.relational:Schema" xmi:id="_isoer3lfEe65NalLni4mbw" name="production"/>
  </orgomg.cwm.resource.relational:Catalog>
</xmi:XMI>
