<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:TalendMetadata="http://www.talend.org/metadata/connection/2010" xmlns:orgomg.cwm.resource.relational="http:///orgomg/cwm/resource/relational.ecore">
  <TalendMetadata:DatabaseConnection xmi:id="_UklkoFL5Ee6_H4_gEeRGPQ" name="Demo_Sql_con" id="_-IFcAFLwEe6_H4_gEeRGPQ" label="Demo_Sql_con" dataPackage="_UklkrlL5Ee6_H4_gEeRGPQ" DatabaseType="Microsoft SQL Server" DriverClass="net.sourceforge.jtds.jdbc.Driver" URL="jdbc:jtds:sqlserver://20.204.123.250:1433/Talend_Demo_DB;" dbVersionString="JTDS" Port="1433" Username="qdimainuser" Password="enc:system.encryption.key.v1:zkRh+ckaa4RkljCxnyU3196HV3Q1mhpE8eo7bK/X01TGuNeJio3sYw==" ServerName="20.204.123.250" DatasourceName="" FileFieldName="" SID="Talend_Demo_DB" SqlSynthax="" StringQuote="" NullChar="" DbmsId="id_MSSQL" ProductId="SQL_SERVER" AdditionalParams="" StandardSQL="true" SQLMode="false" UiSchema="sales" supportNLS="false">
    <taggedValue xmi:id="_UklkoVL5Ee6_H4_gEeRGPQ" tag="Is Conn Need Reload" value="true"/>
    <taggedValue xmi:id="_UklkolL5Ee6_H4_gEeRGPQ" tag="package filter" value=""/>
    <taggedValue xmi:id="_Uklko1L5Ee6_H4_gEeRGPQ" tag="Status" value=""/>
    <taggedValue xmi:id="_UklkpFL5Ee6_H4_gEeRGPQ" tag="Version" value="0.1"/>
    <taggedValue xmi:id="_UklkpVL5Ee6_H4_gEeRGPQ" tag="Purpose" value=""/>
    <taggedValue xmi:id="_UklkplL5Ee6_H4_gEeRGPQ" tag="Description" value=""/>
    <taggedValue xmi:id="_Uklkp1L5Ee6_H4_gEeRGPQ" tag="Author" value=""/>
    <taggedValue xmi:id="_UklkqFL5Ee6_H4_gEeRGPQ" tag="otherParameter"/>
    <taggedValue xmi:id="_UklkqVL5Ee6_H4_gEeRGPQ" tag="DB ProductName" value="Microsoft SQL Server"/>
    <taggedValue xmi:id="_UklkqlL5Ee6_H4_gEeRGPQ" tag="DB ProductVersion" value="15.00.2000"/>
    <taggedValue xmi:id="_Uklkq1L5Ee6_H4_gEeRGPQ" tag="DB IdentifierQuoteString" value="&quot;"/>
    <parameters xmi:id="_UklkrFL5Ee6_H4_gEeRGPQ" key="CONN_PARA_KEY_USERNAME" value="qdimainuser"/>
    <parameters xmi:id="_UklkrVL5Ee6_H4_gEeRGPQ" key="CONN_PARA_KEY_MAPRDB_TABLE_NS_MAPPING" value=""/>
  </TalendMetadata:DatabaseConnection>
  <orgomg.cwm.resource.relational:Catalog xmi:id="_UklkrlL5Ee6_H4_gEeRGPQ" name="Talend_Demo_DB" dataManager="_UklkoFL5Ee6_H4_gEeRGPQ">
    <ownedElement xsi:type="orgomg.cwm.resource.relational:Schema" xmi:id="_Uklkr1L5Ee6_H4_gEeRGPQ" name="sales"/>
  </orgomg.cwm.resource.relational:Catalog>
</xmi:XMI>
