<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:TalendMetadata="http://www.talend.org/metadata/connection/2010" xmlns:orgomg.cwm.resource.relational="http:///orgomg/cwm/resource/relational.ecore">
  <TalendMetadata:DatabaseConnection xmi:id="_ftQTAEJiEe6E-ojWbxevwA" name="MrunalDumsqlserver" id="_wAZXYDwtEe6vHL-ChQZPrw" label="MrunalDumsqlserver" dataPackage="_ftQTDkJiEe6E-ojWbxevwA" DatabaseType="Microsoft SQL Server" DriverJarPath="" DriverClass="net.sourceforge.jtds.jdbc.Driver" URL="jdbc:jtds:sqlserver://20.204.123.250:1433/dummy;" dbVersionString="JTDS" Port="1433" Username="qdimainuser" Password="enc:system.encryption.key.v1:KdoyB2km3x8UIEYo3g2/9ydnpjNay6gpYlyOGWwazmZRDdev5y00ZQ==" ServerName="20.204.123.250" DatasourceName="" FileFieldName="" SID="dummy" SqlSynthax="" StringQuote="" NullChar="" DbmsId="id_MSSQL" ProductId="SQL_SERVER" AdditionalParams="" StandardSQL="true" SQLMode="false" UiSchema="dbo" supportNLS="false">
    <taggedValue href="Mrunal/MrunalDumsqlserver_0.1.item#_5Lo-8TwtEe6vHL-ChQZPrw"/>
    <taggedValue href="Mrunal/MrunalDumsqlserver_0.1.item#_5MZM4DwtEe6vHL-ChQZPrw"/>
    <taggedValue href="Mrunal/MrunalDumsqlserver_0.1.item#_5MiW0DwtEe6vHL-ChQZPrw"/>
    <taggedValue href="Mrunal/MrunalDumsqlserver_0.1.item#_5MiW0TwtEe6vHL-ChQZPrw"/>
    <taggedValue href="Mrunal/MrunalDumsqlserver_0.1.item#_5MiW0jwtEe6vHL-ChQZPrw"/>
    <taggedValue href="Mrunal/MrunalDumsqlserver_0.1.item#_5MiW0zwtEe6vHL-ChQZPrw"/>
    <taggedValue href="Mrunal/MrunalDumsqlserver_0.1.item#_5MiW1DwtEe6vHL-ChQZPrw"/>
    <taggedValue href="Mrunal/MrunalDumsqlserver_0.1.item#_5MiW1TwtEe6vHL-ChQZPrw"/>
    <taggedValue href="Mrunal/MrunalDumsqlserver_0.1.item#_5OVtoDwtEe6vHL-ChQZPrw"/>
    <taggedValue href="Mrunal/MrunalDumsqlserver_0.1.item#_5OVtoTwtEe6vHL-ChQZPrw"/>
    <taggedValue href="Mrunal/MrunalDumsqlserver_0.1.item#_5OVtojwtEe6vHL-ChQZPrw"/>
    <parameters href="Mrunal/MrunalDumsqlserver_0.1.item#_5Lo-8jwtEe6vHL-ChQZPrw"/>
    <parameters href="Mrunal/MrunalDumsqlserver_0.1.item#_1n9VcDwwEe6vHL-ChQZPrw"/>
  </TalendMetadata:DatabaseConnection>
  <orgomg.cwm.resource.relational:Catalog xmi:id="_ftQTDkJiEe6E-ojWbxevwA" name="dummy">
    <ownedElement xsi:type="orgomg.cwm.resource.relational:Schema" xmi:id="_ftQTD0JiEe6E-ojWbxevwA" name="dbo"/>
    <dataManager href="Mrunal/MrunalDumsqlserver_0.1.item#_5Lo-8DwtEe6vHL-ChQZPrw"/>
    <dataManager href="Mrunal/MrunalDumsqlserver_0.1.item#_5Lo-8DwtEe6vHL-ChQZPrw"/>
  </orgomg.cwm.resource.relational:Catalog>
</xmi:XMI>
